export const ErrorCode = {
   // Auth
   INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
   EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
   INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
   REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',

   // Bookmarks
   BOOKMARK_NOT_FOUND: 'BOOKMARK_NOT_FOUND',

   // Collections
   COLLECTION_NOT_FOUND: 'COLLECTION_NOT_FOUND',
   COLLECTION_NESTING_NOT_ALLOWED: 'COLLECTION_NESTING_NOT_ALLOWED',

   // General
   UNAUTHORIZED: 'UNAUTHORIZED',
   FORBIDDEN: 'FORBIDDEN',
   NOT_FOUND: 'NOT_FOUND',
   VALIDATION_ERROR: 'VALIDATION_ERROR',
   INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
